// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID               pgtype.UUID        `json:"id"`
	ClerkUserID      string             `json:"clerk_user_id"`
	OriginalFilename string             `json:"original_filename"`
	InputObjectKey   string             `json:"input_object_key"`
	OutputObjectKey  pgtype.Text        `json:"output_object_key"`
	PageCount        pgtype.Int4        `json:"page_count"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DocumentPage struct {
	ID             pgtype.UUID        `json:"id"`
	DocumentID     pgtype.UUID        `json:"document_id"`
	PageNumber     int32              `json:"page_number"`
	ImageObjectKey string             `json:"image_object_key"`
	ExtractedJson  []byte             `json:"extracted_json"`
	OcrResult      []byte             `json:"ocr_result"`
	EmbeddedText   pgtype.Text        `json:"embedded_text"`
	Status         string             `json:"status"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID          pgtype.UUID        `json:"id"`
	DocumentID  pgtype.UUID        `json:"document_id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       pgtype.Text        `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
