// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    clerk_user_id, original_filename, input_object_key, status
) VALUES (
    $1, $2, $3, 'uploaded'
)
RETURNING id, clerk_user_id, original_filename, input_object_key, status, created_at, updated_at
`

type CreateDocumentParams struct {
	ClerkUserID      string `json:"clerk_user_id"`
	OriginalFilename string `json:"original_filename"`
	InputObjectKey   string `json:"input_object_key"`
}

type CreateDocumentRow struct {
	ID               pgtype.UUID        `json:"id"`
	ClerkUserID      string             `json:"clerk_user_id"`
	OriginalFilename string             `json:"original_filename"`
	InputObjectKey   string             `json:"input_object_key"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.ClerkUserID, arg.OriginalFilename, arg.InputObjectKey)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.OriginalFilename,
		&i.InputObjectKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (
    document_id, type, status
) VALUES (
    $1, $2, 'pending'
)
RETURNING id, document_id, type, status, created_at
`

type EnqueueJobParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	Type       string      `json:"type"`
}

type EnqueueJobRow struct {
	ID         pgtype.UUID        `json:"id"`
	DocumentID pgtype.UUID        `json:"document_id"`
	Type       string             `json:"type"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error) {
	row := q.db.QueryRow(ctx, enqueueJob, arg.DocumentID, arg.Type)
	var i EnqueueJobRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, clerk_user_id, original_filename, input_object_key, output_object_key, page_count, status, created_at, updated_at 
FROM documents 
WHERE id = $1 AND clerk_user_id = $2
`

type GetDocumentParams struct {
	ID          pgtype.UUID `json:"id"`
	ClerkUserID string      `json:"clerk_user_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.ClerkUserID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.OriginalFilename,
		&i.InputObjectKey,
		&i.OutputObjectKey,
		&i.PageCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
