// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error)
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error)
}

var _ Querier = (*Queries)(nil)
